import { ChakraProvider } from '@chakra-ui/react'
import { Box } from '@chakra-ui/react'
import type { Metadata } from 'next'
import { Header } from '@/components'

import '@/styles/global.css'

export const metadata: Metadata = {
  title: 'Laptop',
  description: 'Generated by duonglavish'
}

const styles = {
  container: {
    w: '100%',
    h: '100%'
  }
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          <Box {...styles.container}>
            <Header />
            {children}
          </Box>
        </ChakraProvider>
      </body>
    </html>
  )
}
