import { ChakraProvider } from '@chakra-ui/react'
import type { Metadata } from 'next'

import './global.css'

export const metadata: Metadata = {
  title: 'Laptop',
  description: 'Generated by duonglavish'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>{children}</ChakraProvider>
      </body>
    </html>
  )
}
